version: "3.3"
services:
    db:
        #platform: linux/arm64
        build: ./db/
        ports:
            - 54321:5432
        expose:
            - 54321
        environment:
            - PASSWORD_AUTHENTICATION=md5
            - POSTGRES_DB=testdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgresspass
            - ALLOW_IP_RANGE=0.0.0.0/0
        restart: on-failure
        healthcheck:
            test: "exit 0"